### ISSUE TITLE
DragAdorner InitializeComponent XamlParseException on TextBlock

### ISSUE THREAD

**Issue by ChrisTorng** [PassivePicasso/Claudable#2]
Clone and run in VS 2022, got this:
![image](https://github.com/user-attachments/assets/37a32571-c185-4e71-9469-a01cb7786792)

```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Initialization of 'System.Windows.Controls.TextBlock' threw an exception.' Line number '26' and line position '36'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Claudable.Windows.DragAdorner.InitializeComponent() in D:\GitHub\ChrisTorng\cloned\Claudable\Claudable\Windows\DragAdorner.xaml:line 1

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
IndexOutOfRangeException: Index was outside the bounds of the array.
```

Seems like error on `TextBlock Text="{Binding Path}"`:
![image](https://github.com/user-attachments/assets/22ad5315-537b-489e-ab9c-0983f71c45f2)

**Comment by PassivePicasso** [comment]
I've been unable to reproduce this issue unfortunately, even removing the temporary files that claudable creates which would affect that startup state I haven't reproduced this issue.

This may be affected by OS version, or maybe installed .NET SDK?

**Comment by ChrisTorng** [comment]
I found this: [When using .NET9 pre7 build and run, will throw System.Windows.Markup.XamlParseException](https://github.com/dotnet/wpf/issues/9582).
I'm using newest [Microsoft Visual Studio 2022 17.12.0 Preview 1.0](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#17.11.0-pre.2.1). I changed the Target Framework to 9.0 then it worked. It should be a bug in .NET SDK 9 preview. Close this issue.
